version: "3.8"
services:
  # redis:
  #   image: redis:6
  #   container_name: seener_redis
  #   ports:
  #     - "6379:6379"
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #   volumes:
  #     - ./docker-data/redis/etc/redis:/usr/local/etc/redis
  #     - ./docker-data/redis/data:/data
  #   command: redis-server /usr/local/etc/redis/redis.conf
  app:
    build: .
    container_name: TaskBuy
    ports:
      - 3001:3001
    env_file: .env
    depends_on:
      - db
  db:
    image: postgres:13.3
    container_name: db_postgres
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: asd8235ms0vfg
      POSTGRES_DB: main
    volumes:
      - ./docker-data/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U main"]
      interval: 10s
      timeout: 5s
      retries: 5

